# Generated by Django 5.1.1 on 2025-02-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cart', models.CharField(max_length=50, verbose_name='Nombre de Tarjeta')),
                ('card_number', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Número de Tarjeta')),
                ('expiry_month', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Mes de Expiración')),
                ('expiry_year', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Año de Expiración')),
                ('cvv', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='CVV')),
            ],
        ),
    ]
