# Generated by Django 5.1.1 on 2024-10-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article_name',
            field=models.TextField(max_length=50, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(max_length=50, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(max_length=10, null=True, verbose_name='precio'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=50, null=True, verbose_name='talla'),
        ),
    ]
