# Generated by Django 5.1.1 on 2025-01-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('entradas', models.IntegerField(null='True')),
                ('salidas', models.IntegerField(null='True')),
                ('stock_actual', models.IntegerField(null='True')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='article_name',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default='True', null=True, verbose_name='disponible'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.TextField(max_length=100, null=True, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.TextField(max_length=10, null=True, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(max_length=100, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=10, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=100, null=True, verbose_name='talla'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='costo_unitario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='precio'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
