# Generated by Django 5.1.1 on 2025-01-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_inventario_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.TextField(max_length=100, null=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=100, null=True, verbose_name='nombre'),
        ),
    ]
