# Generated by Django 5.1.1 on 2025-01-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='costo_unitario'),
        ),
    ]
