# Generated by Django 5.1.1 on 2025-01-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='precio'),
        ),
    ]
