# Generated by Django 5.1.1 on 2025-01-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.TextField(null=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(null=True, verbose_name='talla'),
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.categoria'),
        ),
    ]
