# Generated by Django 5.1.1 on 2025-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_categoria_alter_product_brand_alter_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre_categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.TextField(null=True, unique=True),
        ),
    ]
