# Generated by Django 5.1.1 on 2025-01-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_categoria_nombre_categoria_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.TextField(null=True),
        ),
    ]
