# Generated by Django 5.1.1 on 2025-02-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_order_delete_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
